Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [1]:
import numpy as np

In [12]:
x = np.arange(12, 24)

In [13]:
x

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.


In [29]:
y1 = x.reshape(2,6)
y2 = x.reshape(6,2)
y3 = x.reshape(1,12)
y4 = x.reshape(4,3)
y5 = x.reshape(3,4)

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [31]:
y1 = x.reshape(2,-1)
y2 = x.reshape(6,-1)
y3 = x.reshape(1,-1)
y4 = x.reshape(-1,3)
y5 = x.reshape(-1,4)

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


да

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [38]:
a = np.random.sample((3,4))

In [39]:
a

array([[0.16400706, 0.40583854, 0.21994539, 0.85711506],
       [0.78884578, 0.04918641, 0.04600824, 0.03519999],
       [0.86997916, 0.10655358, 0.24646179, 0.91214644]])

In [40]:
a.size

12

In [45]:
b = a.flatten()

In [49]:
b

array([0.16400706, 0.40583854, 0.21994539, 0.85711506, 0.78884578,
       0.04918641, 0.04600824, 0.03519999, 0.86997916, 0.10655358,
       0.24646179, 0.91214644])

In [50]:
b.size

12

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.


In [63]:
b = np.arange(0,20,2)

In [64]:
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [67]:
a = np.flip(b)

In [68]:
a

array([18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [73]:
b = np.arange(2,21,2)

In [74]:
c = np.flip(b)

In [87]:
b = c.reshape(-1,1)

In [88]:
b

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

Ответ: массив а - одномерный, массив b - многомерный

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10

In [89]:
a = np.zeros((2,2))
b = np.ones((3,2))

In [91]:
c = np.vstack((a,b))

In [92]:
c

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [93]:
c.size

10

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [97]:
a = np.arange(0,12)

In [98]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [101]:
A = a.reshape(4,3)

In [102]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [103]:
At = A.T

In [106]:
B = A.dot(At)

In [109]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [111]:
np.linalg.det(B)

0.0

In [113]:
B.shape

(4, 4)

Ответ: размер матрицы B - 4x4, рассчитать обратную матрицу нельзя так как определитель равен 0.